env:
  es6: true
  node: true

plugins:
  - wdio

parser: 'babel-eslint'

extends:
  - 'airbnb-base'
  - 'plugin:wdio/recommended'
  - 'prettier'

globals:
  assert: true
  expect: true

parserOptions:
  ecmaVersion: 6

root: true

rules:
  global-require: 'off'
  import/no-extraneous-dependencies: 0
  indent:
    - 'error'
    - 2
    - SwitchCase: 1
  lines-between-class-members:
    exceptAfterSingleLine: true
  max-len:
    - 'error'
    - 120
    - ignorePattern: '\s*\/\^(.*)\$\/,$'
  new-cap:
    - 'error'
    - newIsCap: true
      capIsNewExceptions:
        - 'Given'
        - 'When'
        - 'Then'
  require-jsdoc:
    - 'warn'
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
  strict: 'off'
  valid-jsdoc:
    - 'error'
    - requireReturn: false
      matchDescription: '.+'
